# fly.toml app configuration file generated for server-greenlet on 2023-12-20T15:20:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "server-greenlet"
primary_region = "mad"

[build]

[http_service]
  internal_port = 5005
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
